FROM ubuntu:20.04

# Install apt packages
RUN apt-get update && \
    apt-get install -y \
        wget curl git vim unzip \
        gcc g++ make \
    && \
    apt-get autoclean

# Set timezone
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && \
    apt-get install -yq tzdata && \
    dpkg-reconfigure -f noninteractive tzdata && \
    ln -fs /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    apt-get autoclean

# Install miniconda
RUN wget -q \
    https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh \
    && bash Miniconda3-latest-Linux-x86_64.sh -b -p /opt/miniconda \
    && rm -f Miniconda3-latest-Linux-x86_64.sh

# Download protoc
RUN mkdir -p /opt/protoc && cd /opt/protoc && \
    curl -LjO https://github.com/protocolbuffers/protobuf/releases/download/v31.1/protoc-31.1-linux-x86_64.zip \
    && unzip protoc-31.1-linux-x86_64.zip \
    && rm -f protoc-31.1-linux-x86_64.zip \
    && chmod +x bin/protoc

# Update in bashrc
RUN echo "source /opt/miniconda/etc/profile.d/conda.sh" >> /root/.bashrc && \
    echo "conda deactivate" >> /root/.bashrc && \
    ln -s /opt/protoc/bin/protoc /usr/bin/protoc

# Prepare conda env
RUN . /opt/miniconda/etc/profile.d/conda.sh && \
    conda config --add channels conda-forge && \
    conda tos accept && \
    conda create -n audio2face python=3.10 -y && \
    conda activate audio2face && \
    conda install pytorch==2.4.1 \
        torchvision==0.19.1 torchaudio==2.4.1 \
        pytorch-cuda=12.1 -c pytorch -c nvidia -y && \
    pip install toml-to-requirements && \
    pip cache purge && \
    conda clean --all

# COPY pyproject.toml and export requirements
# onnxruntime-gpu requires cudnn9, which is installed by pytorch 2.4.1,
# do not use an image with cudnn8
COPY pyproject.toml /opt/pyproject.toml
RUN . /opt/miniconda/etc/profile.d/conda.sh && \
    conda activate audio2face && \
    cd /opt && \
    toml-to-req --toml-file pyproject.toml --optional-lists dev && \
    sed -i '/^onnxruntime$/d' requirements.txt && \
    pip install -r requirements.txt && \
    pip install onnxruntime-gpu==1.22.0 && \
    pip cache purge

# COPY code
COPY . /workspace/audio2face
# Install code
RUN . /opt/miniconda/etc/profile.d/conda.sh && \
    conda activate audio2face && \
    cd /workspace/audio2face && \
    pip install . && \
    pip cache purge

# Set working directory
WORKDIR /workspace/audio2face

# Set env var
ENV LD_LIBRARY_PATH=/opt/miniconda/pkgs/pytorch-2.4.1-py3.10_cuda12.1_cudnn9.1.0_0/lib/python3.10/site-packages/torch/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64

# Set entrypoint
ENTRYPOINT ["/bin/bash", "-c", "source /opt/miniconda/etc/profile.d/conda.sh && conda activate audio2face && python main.py --config_path configs/cuda.py"]